:et nocompatible

" Color Scheme
syntax on
filetype plugin indent on
colorscheme elflord
set background=dark

" General settings
set undofile
set ttyfast
set wildmode=list:longest
set wildmenu
set showcmd
set relativenumber
set number
set vb

" Text formatting
set nowrap
set textwidth=80
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab
set autoindent
set smartindent

" Status line
set ruler
set showmode
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

" Searching
set showmatch
set ignorecase
set smartcase
set hlsearch
set incsearch
set gdefault

" Window controls
set report=0
set scrolloff=10
set showtabline=2
set laststatus=2

let mapleader=" "
let maplocalleader="\\"

" Nativation
imap jj <Esc>
nnoremap j gj
nnoremap k gk

" Spellcheck
nnoremap <buffer> <C-l> [s1z=<C-O>
inoremap <buffer> <C-l> <Esc>[s1z=`]a

" Terminal
noremap <C-w>t :term<cr>

" Quickfix
nnoremap <leader>cn :cnext<cr>
nnoremap <leader>cp :cprevious<cr>
nnoremap <leader>co :copen<cr>
nnoremap <leader>cc :cclose<cr>

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 0
let g:netrw_altv = 1
let g:netrw_winsize = 15
